### ISSUE TITLE
4장 코드작성 TODO

### ISSUE THREAD

**Issue by Irisation23** [cowaine/is-my-code-that-strange#27]
### 4.1 재할당

- [x] 4.1.1 불변 변수로 만들어서 재할당 막기
- [x] 4.1.2 매개변수도 불변으로 만들기

### 4.2 가변으로 인해 발생하는 의도하지 않은 영향

- [x] 4.2.1 사례 1: 가변 인스턴스 재사용하기
- [x] 4.2.2 사례 2: 함수로 가변 인스턴스 조작하기
- [x] 4.2.3 부수효과의 단점
- [x] 4.2.4 함수의 영향 범위 한정하기
- [x] 4.2.5 불변으로 만들어서 예기치 못한 동작 막기

### 4.3 불변과 가변은 어떻게 다루어야 할까?

- [x] 4.3.1 기본적으로 불변으로
- [x] 4.3.2 가변으로 설계해야 하는 경우
- [x] 4.3.3 상태를 변경하는 메서드 설계하기
- [x] 4.3.4 코드 외부와 데이터 교환은 국소화하기

**Comment by Irisation23** [comment]
[간단한 정리 md 링크](https://github.com/cowaine/is-my-code-that-strange/tree/main/irisation23/readme/irisation23-README.md)
