### ISSUE TITLE
5장 코드작성 TODO

### ISSUE THREAD

**Issue by Irisation23** [cowaine/is-my-code-that-strange#28]
### 5.1 static 메서드 오용

- [x] 5.1.1 static 메서드는 인스턴스 변수를 사용할 수 없음
- [x] 5.1.2 인스턴스 변수를 사용하는 구조로 변경하기
- [x] 5.1.3 인스턴스 메서드인 척하는 static 메서드 주의하기
- [x] 5.1.4 왜 static 메서드를 사용할까?
- [x] 5.1.5 어떠한 상황에서 static 메서드를 사용해야 좋을까?

### 5.2 초기화 로직 분산

- [x] 5.2.1 private 생성자 + 팩토리 메서드를 사용해 목적에 따라 초기화하기
- [x] 5.2.2 생성 로직이 너무 많아지면 팩토리 클래스를 고려해 보자

### 5.3 범용 처리 클래스 (Common/Util)

- [ ] 5.3.1 너무 많은 로직이 한 클래스에 모이는 문제
- [ ] 5.3.2 객체 지향 설계의 기본으로 돌아가기
- [ ] 5.3.3 횡단 관심사

### 5.5 매개변수가 너무 많은 경우

- [ ] 5.5.1 기본 자료형에 대한 집착
- [ ] 5.5.2 의미 있는 단위는 모두 클래스로 만들기

### 5.6 메서드 체인

- [ ] 5.6.1 묻지 말고 명령하기
