### ISSUE TITLE
1장 코드 작성 TODO

### ISSUE THREAD

**Issue by Irisation23** [cowaine/is-my-code-that-strange#5]
# 1장 잘못된 구조의 문제 깨닫기

## 1.1 의미를 알 수 없는 이름

- [x] 1.1 기술 중심 명명
- [x] 1.2 일련번호 명명

## 1.2 이해하기 어렵게 만드는 조건 분기 중첩

- [x] 1.3 여러 번 중첩된 로직
- [x] 1.4 거대한 중첩

## 1.3 수 많은 악마를 만들어 내는 데이터 클래스

- [x] 1.5 데이터 밖에 없는 클래스 구조
- [x] 1.6 ContractManager에 작성된 금액 계산 로직
- ~~1.7 쓰레기 객체~~
- ~~1.8 잘못된 값이 들어간 경우~~

## 1.4 악마 퇴치의 기본

**Comment by Irisation23** [comment]
1.7과 1.8 코드는 의도적 누락임.

**Comment by Irisation23** [comment]
간단한 정리 md 링크
https://github.com/cowaine/is-my-code-that-strange/tree/main/irisation23/readme/irisation23-README.md
