### ISSUE TITLE
2장 코드 작성 TODO

### ISSUE THREAD

**Issue by Irisation23** [cowaine/is-my-code-that-strange#6]
# 2장 설계 첫걸음

## 2.1 의도를 분명히 전달할 수 있는 이름 설계하기

- [x] 2.1 어떤 일을 하는지 이해하기 힘든 로직
- [x] 2.2 의도를 알 수 있는 이름 붙이기

## 2.2 목적별로 변수를 따로 만들어 사용하기

- [x] 2.3 목적별로 변수 만들어 사용하기

## 2.3 단순 나열이 아니라, 의미 있는 것을 모아 메서드로 만들기

- [x] 2.4 의미를 알기 쉽게 메서드로 만들기
- [x] 2.5 메서드를 호출하는 형태로 개선

## 2.4 관련된 데이터와 로직을 클래스로 모으기

- ~~2.6 히트포인트를 단독 변수로 만듬~~
- ~~2.7 어딘가에 구현되어 있는 히트포인트 감소 로직~~
- ~~2.8 어딘가에 구현되어 있는 회복 로직~~
- [x] 2.9 클래스를 활용하면 밀접한 관계를 갖고 있는 데이터와 로직을 묶을 수 있음

**Comment by Irisation23** [comment]
[간단한 정리 md 링크](https://github.com/cowaine/is-my-code-that-strange/tree/main/irisation23/readme/irisation23-README.md)
