### ISSUE TITLE
3장 코드 작성 TODO

### ISSUE THREAD

**Issue by Irisation23** [cowaine/is-my-code-that-strange#7]
# 3장 클래스 설계: 모든것과 연결되는 설계 기반

## 3.2 성숙한 클래스로 성장시키는 설계 기법

- [x] 금액을 나타내는 클래스
- [x] 생성자에서 초기화하기
- [x] 잘못된 값이 전달되어 버린 경우
- [x] 생성자에서 유효성 검사하기
- [x] Money 클래스에 금액을 추가하는 메서드 만들기
- [x] 인스턴스 변수를 계속해서 변경하는 경우
- [x] final을 붙여 불변 변수로 만들기
- [x] 변경된 값을 가진 인스턴스 생성하기
- [x] 메서드 내부에서 매개변수를 변경
- [x] final로 매개변수를 재할당하지 못하게 만들기
- [x] add 메서드의 매개변수도 final로 만들기
- [x] 지역 변수도 불변으로 만들기
- [x] 금액을 의미하지 않는 값을 전달하는 경우
- [x] Money 자료형만 받도록 메서드 수정하기
- [x] add 메서드를 추가로 개선하기
- [x] 금액을 곱하는 메서드가 의미 있을까?

## 3.3 악마 퇴치 효과 검토하기

- [x] 관련 로직을 응집해서 코드 수정 시 버그 발생이 어려워진 Money 클래스

## 3.4 프로그램 구조의 문제 해결에 도움을 주는 디자인 패턴

**Comment by Irisation23** [comment]
[간단한 정리 md 링크](https://github.com/cowaine/is-my-code-that-strange/tree/main/irisation23/readme/irisation23-README.md)
